[package]
name = "fsonline"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
bitflags = { version = "2.13.0", features = ["std"] }
bytes = "1.12.0"
chromiumoxide = "0.9.1"
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.1", features = ["derive", "env"] }
dotenvy = "0.15.7"
foyer = { version = "0.22.3", features = ["serde"] }
futures = "0.3.32"
hyper = "1.10.1"
itertools = "0.15.0"
m3u8-rs = "6.0.0"
md5 = "0.8.0"
moka = { version = "0.12.15", features = ["future"] }
mpeg2ts-reader = "0.18.2"
regex = "1.12.4"
reqwest = { version = "0.13.4", features = ["form", "gzip", "json", "stream"] }
scraper = "0.27.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
thiserror = "2.0.18"
time = { version = "0.3.49", features = ["macros"] }
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = "0.7.18"
tower = "0.5.3"
tower-http = { version = "0.7", features = ["cors", "fs"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "local-time",
    "time",
] }
uuid = { version = "1.23.2", features = ["serde", "v4"] }
